const mongoose = require('mongoose');
const { Category, MenuItem } = require('./models');

async function seedDatabase() {
  try {
    const count = await Category.countDocuments();
    if (count > 0) {
      console.log('✅ Database already seeded, skipping.');
      return;
    }

    console.log('🌱 Seeding categories and menu...');

    // ── CATEGORIES ──────────────────────────────────────
    const categories = await Category.insertMany([
      { name: 'Breakfast',      display_order: 1,  available_from: '07:00', available_to: '11:00', icon: '🌅' },
      { name: 'Snacks',         display_order: 2,  available_from: '15:00', available_to: '19:00', icon: '🍟' },
      { name: 'Soups',          display_order: 3,  icon: '🍲' },
      { name: 'Salads',         display_order: 4,  icon: '🥗' },
      { name: 'Tandoori Zaika', display_order: 5,  icon: '🔥' },
      { name: 'Lunch & Dinner', display_order: 6,  icon: '🍛' },
      { name: 'Chinese',        display_order: 7,  icon: '🥢' },
      { name: 'Rice & Pulao',   display_order: 8,  icon: '🍚' },
      { name: 'Indian Breads',  display_order: 9,  icon: '🫓' },
      { name: 'Raita',          display_order: 10, icon: '🥣' },
      { name: 'Continental',    display_order: 11, icon: '🥩' },
      { name: 'Pasta',          display_order: 12, icon: '🍝' },
      { name: 'Sizzlers',       display_order: 13, icon: '♨️' },
      { name: 'Noodles',        display_order: 14, icon: '🍜' },
      { name: 'Desserts',       display_order: 15, icon: '🍮' },
      { name: 'Beverages',      display_order: 16, icon: '☕' },
    ]);

    // Helper to get category _id by name
    const cat = (name) => categories.find(c => c.name === name)._id;

    // ── MENU ITEMS ───────────────────────────────────────
    await MenuItem.insertMany([

      // BREAKFAST
      { category_id: cat('Breakfast'), subcategory: 'Set Menu', name: 'Continental Breakfast', description: 'Choice of Chilled Juice, Toast/Slice with butter & preserves, Tea/Coffee or Hot Milk', price: 390, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'Set Menu', name: 'American Breakfast', description: 'Chilled Juice, Toast/Slice, Cornflakes/Porridge, Eggs to Order, Coffee', price: 450, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Chilled Juice (Full)', price: 125, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Chilled Juice (Small)', price: 80, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Toast with Butter & Preserves', price: 150, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Cornflakes / Porridge', description: 'With hot or cold milk', price: 150, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Eggs to Order', description: 'Fried / Scrambled / Boiled', price: 125, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'Omelette with Breads', name: 'Plain Omelette', price: 165, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'Omelette with Breads', name: 'Masala Omelette', price: 190, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'Omelette with Breads', name: 'Cheese Omelette', price: 190, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'Omelette with Breads', name: 'Mushroom Omelette', price: 200, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'Omelette with Breads', name: 'Chicken Omelette', price: 105, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Boiled Egg (2 pcs.)', price: 180, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Cheese Garlic Toast', price: 180, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Mushroom on Toast', price: 200, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Plain Prantha', price: 55, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Stuffed Prantha with Pickle', price: 70, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Cheese Prantha', price: 100, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Channa Bhatura', description: '2 pieces', price: 180, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Puri Bhaji', description: '2 pieces', price: 170, is_veg: true },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Egg Bhurji', price: 170, is_veg: false },
      { category_id: cat('Breakfast'), subcategory: 'A-La-Cart', name: 'Plain Slice', description: '2 pieces', price: 25, is_veg: true },

      // SNACKS
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Paneer 65', price: 335, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Finger Chips', price: 200, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Sandwich', price: 145, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Club Sandwich', price: 325, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Cheese Sandwich', price: 200, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Cheese Cutlet', price: 270, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Vegetable Cutlet', price: 200, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Manchurian Dry', price: 335, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Cheese Finger', price: 335, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Peanut Masala', price: 180, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Papad Roll', price: 210, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Cheese Corn Roll', price: 270, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Crumbed Fried Mushroom', price: 300, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Spring Roll', price: 270, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Baby Corn Chilly', price: 290, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Baby Corn Fried', price: 300, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Cocktail Kabab', price: 210, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Chilly Chulbuli', price: 270, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Cheese Cocktail Kabab', price: 325, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Kathi Roll', price: 270, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Mushroom Chatpate', price: 325, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Paneer Chatpate', price: 335, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Hara Bhara Kabab', price: 200, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Chilli Honey Cauliflower', price: 280, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Mushroom Duplex', price: 325, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Veg Pakoda', price: 225, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Vegetarian', name: 'Paneer Pakoda', price: 335, is_veg: true },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Chicken Sandwich', price: 325, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Egg Sandwich', price: 225, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Club Sandwich (Chicken)', price: 400, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Chicken Cutlet', price: 400, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Fish Finger with Tartar Sauce', price: 420, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Chicken Pakora', price: 420, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Fish Pakora', price: 420, is_veg: false },
      { category_id: cat('Snacks'), subcategory: 'Non-Vegetarian', name: 'Fish Amritsari', price: 420, is_veg: false },

      // SOUPS
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Lemon Coriander Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Veg Manchow Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Veg Hot N Sour Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Veg Sweet Corn Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Veg Talumein Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Cream of Mushroom', price: 140, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Cream of Almond', price: 185, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Cream of Tomato', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Cream of Vegetable', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Tomato Dhaniya Shorba', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Vegetarian', name: 'Veg Clear Soup', price: 130, is_veg: true },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Chicken Manchow Soup', price: 210, is_veg: false },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Chicken Hot N Sour Soup', price: 210, is_veg: false },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Chicken Sweet Corn Soup', price: 210, is_veg: false },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Chicken Talumein Soup', price: 225, is_veg: false },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Cream of Chicken', price: 210, is_veg: false },
      { category_id: cat('Soups'), subcategory: 'Non-Vegetarian', name: 'Chicken Clear Soup', price: 210, is_veg: false },

      // SALADS
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Cucumber with Hung Curd Salad', price: 185, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Green Salad', price: 145, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Cucumber Salad', price: 125, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Russian Salad', price: 215, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Cheese Macaroni Salad', price: 200, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Fruit Salad', price: 270, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Aloo Chana Chat', price: 210, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Kachumber Salad', price: 180, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Papad', price: 35, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Papad Masala', price: 70, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Vegetarian', name: 'Greek Salad', price: 160, is_veg: true },
      { category_id: cat('Salads'), subcategory: 'Non-Vegetarian', name: 'Egg Chat', price: 210, is_veg: false },
      { category_id: cat('Salads'), subcategory: 'Non-Vegetarian', name: 'Chicken Chat', price: 325, is_veg: false },

      // TANDOORI ZAIKA
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Malai Tikka', price: 335, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Lashooni Tikka', price: 310, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Tikka', price: 335, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Tikka Do Ranga', price: 350, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Makhmali Seekh', price: 310, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Shabnam Mushroom', price: 325, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Achari Tikka', price: 325, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Paneer Hariyali Tikka', price: 325, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Veg Seekh Kabab', price: 270, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Cheese Seekh Kabab', price: 350, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Mushroom Kabab', price: 350, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Aloo Nazakat', price: 270, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Tandoori Sangam (Veg)', price: 540, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Tandoori Gobhi Achari', price: 270, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Vegetarian', name: 'Pineapple Tikka', price: 335, is_veg: true },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Tikka', price: 530, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Malai Tikka', price: 550, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Afgani', price: 730, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Achari Tikka', price: 550, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Sheekh Kabab', price: 530, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Tandoori (Full)', price: 670, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Chicken Tandoori (Half)', price: 400, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Kalami Kabab (4 pcs.)', price: 600, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Tangri Kabab (4 pcs.)', price: 600, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Stuffed Tangri (4 pcs.)', price: 625, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Fish Tikka (Seasonal)', price: 490, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Fish Achari Tikka (Seasonal)', price: 490, is_veg: false },
      { category_id: cat('Tandoori Zaika'), subcategory: 'Non-Vegetarian', name: 'Tandoori Sangam (Non Veg.)', price: 880, is_veg: false },

      // LUNCH & DINNER
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Riviera Special', description: 'Chef\'s special recipe', price: 475, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Pasanda', description: 'Stuffed paneer pieces cooked in royal khoya gravy', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Shahi Paneer', description: 'Diced cottage cheese cooked in rich creamy gravy', price: 365, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Kadhai Paneer', price: 385, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Bhujia', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Cheese Chatniwala', price: 370, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Mutter Paneer', price: 335, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Tikka Butter Masala', price: 385, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Malai Methi', price: 400, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Handi', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Lababdar', price: 390, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Makhani', price: 375, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Palak Paneer', price: 375, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Paneer Taka-Tak', price: 335, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Mushroom Do Pyaza', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Kadhai Mushroom', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Mushroom Masala', price: 350, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Mushroom Makhani', price: 365, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Palak Kofta', price: 390, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Malai Kofta', price: 280, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Vegetable Jalfrezi', price: 385, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Mix Veg.', price: 295, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Veg Makhani', price: 325, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Gobhi Masala', price: 295, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Aloo Mutter', price: 270, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Zeera Aloo', price: 260, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Channa Masala', price: 335, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Dal Makhani', price: 295, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Dal Black Punjabi Tadka', price: 295, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Dal Tadka Yellow', price: 280, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Navratan Korma', price: 390, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Palak Corn', price: 375, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Vegetarian', name: 'Veg Gravy', price: 95, is_veg: true },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Butter Chicken (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Butter Chicken (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Masala (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Masala (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Kadhai (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Kadhai (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Curry', price: 370, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Tikka Butter Masala', price: 630, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Handi (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Handi (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Kali Mirch (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Kali Mirch (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Rara (Full)', price: 795, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Rara (Half)', price: 475, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Chatniwala', price: 630, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Chicken Patiala', price: 700, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Mutton Rogan Josh', price: 540, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Mutton Curry', price: 540, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Mutton Rara', price: 540, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Egg Curry', price: 310, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Fish Curry', price: 550, is_veg: false },
      { category_id: cat('Lunch & Dinner'), subcategory: 'Non-Vegetarian', name: 'Non Veg Gravy', price: 125, is_veg: false },

      // CHINESE
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Cheese Chilly', price: 350, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Veg Manchurian', price: 350, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Veg Choupasy', price: 365, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Mushroom Chilly', price: 435, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Veg Sweet N Sour', price: 350, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Channa Chilly', price: 270, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Vegetarian', name: 'Potato Chilly', price: 270, is_veg: true },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Chilly (Full)', price: 795, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Chilly (Half)', price: 475, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Manchurian', price: 500, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Sweet N Sour', price: 500, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Hong-Kong', price: 500, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Ginger (Full)', price: 795, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Ginger (Half)', price: 475, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Garlic (Full)', price: 795, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken Garlic (Half)', price: 475, is_veg: false },
      { category_id: cat('Chinese'), subcategory: 'Non-Vegetarian', name: 'Chicken 65', price: 500, is_veg: false },

      // RICE & PULAO
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Plain Rice', price: 190, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Vegetable Biryani', price: 300, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Hydrabadi Biryani (Veg.)', price: 335, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Jeera Pulao', price: 210, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Peas Pulao', price: 210, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Veg Pulao', price: 210, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Cheese Pulao', price: 235, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Mushroom Fried Rice', price: 310, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Vegetarian', name: 'Vegetable Fried Rice', price: 280, is_veg: true },
      { category_id: cat('Rice & Pulao'), subcategory: 'Non-Vegetarian', name: 'Chicken Biryani', price: 475, is_veg: false },
      { category_id: cat('Rice & Pulao'), subcategory: 'Non-Vegetarian', name: 'Egg Biryani', price: 360, is_veg: false },
      { category_id: cat('Rice & Pulao'), subcategory: 'Non-Vegetarian', name: 'Hydrabadi Biryani (Mutton)', price: 560, is_veg: false },
      { category_id: cat('Rice & Pulao'), subcategory: 'Non-Vegetarian', name: 'Chicken Fried Rice', price: 480, is_veg: false },
      { category_id: cat('Rice & Pulao'), subcategory: 'Non-Vegetarian', name: 'Egg Fried Rice', price: 350, is_veg: false },

      // INDIAN BREADS
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Butter Roti', price: 30, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Missi Roti', price: 35, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Lachha Prantha', price: 55, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Butter Naan', price: 70, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Plain Naan', price: 95, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Pudina Prantha', price: 75, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Stuffed Prantha', price: 75, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Garlic Naan', price: 80, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Onion Kulcha', price: 95, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Potato Kulcha', price: 100, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Amritsari Kulcha', price: 90, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Cheese Naan', price: 125, is_veg: true },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Keema Naan with Gravy', price: 270, is_veg: false },
      { category_id: cat('Indian Breads'), subcategory: 'Breads', name: 'Cheese Prantha with Chinese Gravy', price: 475, is_veg: true },

      // RAITA
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Curd (Processed)', price: 100, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Mix Raita', price: 145, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Mint Raita', price: 145, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Aloo Raita', price: 145, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Pineapple Raita', price: 170, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Cucumber Raita', price: 145, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Boondi Raita', price: 145, is_veg: true },
      { category_id: cat('Raita'), subcategory: 'Raita', name: 'Fruit Raita', price: 170, is_veg: true },

      // CONTINENTAL
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Baked Special Riviera', price: 325, is_veg: true },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Boiled Veg.', price: 475, is_veg: true },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Cottage Cheese Shashlik', price: 475, is_veg: true },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Chicken Shashlik', price: 540, is_veg: false },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Imperial Chicken', price: 600, is_veg: false },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Grilled Chicken', price: 600, is_veg: false },
      { category_id: cat('Continental'), subcategory: 'Main Course', name: 'Chicken Steak in Pepper Sauce', price: 475, is_veg: false },

      // PASTA
      { category_id: cat('Pasta'), subcategory: 'Pasta', name: 'Spaghetti with Cheese', price: 415, is_veg: true },
      { category_id: cat('Pasta'), subcategory: 'Pasta', name: 'Spaghetti with Tomato Sauce', price: 415, is_veg: true },
      { category_id: cat('Pasta'), subcategory: 'Pasta', name: 'Baked Macaroni', price: 415, is_veg: true },

      // SIZZLERS
      { category_id: cat('Sizzlers'), subcategory: 'Sizzlers', name: 'Veg Sizzler', price: 400, is_veg: true },
      { category_id: cat('Sizzlers'), subcategory: 'Sizzlers', name: 'Cheese Sizzler', price: 475, is_veg: true },
      { category_id: cat('Sizzlers'), subcategory: 'Sizzlers', name: 'Chicken Sizzler', price: 570, is_veg: false },
      { category_id: cat('Sizzlers'), subcategory: 'Sizzlers', name: 'Chicken Stick Sizzler', price: 570, is_veg: false },

      // NOODLES
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Riviera Special Noodles', price: 350, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Mushroom Noodles', price: 310, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Vegetable Noodles', price: 280, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Singapori Noodles', price: 300, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Cheese Noodles', price: 315, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Vegetarian', name: 'Hakka Noodles', price: 300, is_veg: true },
      { category_id: cat('Noodles'), subcategory: 'Non-Vegetarian', name: 'Egg Noodles', price: 310, is_veg: false },
      { category_id: cat('Noodles'), subcategory: 'Non-Vegetarian', name: 'Chicken Noodles', price: 375, is_veg: false },

      // DESSERTS
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Kaju Pista Ice Cream', price: 135, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Vanilla Ice Cream', price: 95, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Strawberry Ice Cream', price: 95, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Chocolate Ice Cream', price: 95, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Butter Scotch Ice Cream', price: 105, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Frozen Desserts', name: 'Tooty Frooty Ice Cream', price: 160, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Desserts', name: 'Gulab Jamun (2 pcs.)', price: 80, is_veg: true },
      { category_id: cat('Desserts'), subcategory: 'Desserts', name: 'Gajjar Halwa', price: 125, is_veg: true },

      // BEVERAGES
      { category_id: cat('Beverages'), subcategory: 'Tea & Coffee', name: 'Tea (Full Set)', price: 160, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Tea & Coffee', name: 'Tea (Half Set)', price: 80, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Tea & Coffee', name: 'Lemon Tea', price: 40, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Tea & Coffee', name: 'Tea (Per Cup)', price: 45, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Tea & Coffee', name: 'Coffee', price: 70, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Flavoured Milk', price: 100, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Cold Coffee', price: 140, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Cold Coffee with Ice Cream', price: 150, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Lassi (Sweet / Salted)', price: 90, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Milk Shake', price: 140, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Fresh Lime Soda', price: 60, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Fresh Lime Water', price: 45, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Cold Beverages', name: 'Jal Jeera', price: 70, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Soft Drinks', name: 'Packed Water', price: 30, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Soft Drinks', name: 'Aerated Drinks', price: 45, is_veg: true },
      { category_id: cat('Beverages'), subcategory: 'Soft Drinks', name: 'Soda', price: 45, is_veg: true },
    ]);

    console.log('✅ Menu seeded successfully!');
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  }
}

module.exports = seedDatabase;